import { InfoCard, InfoPageLayout } from "@/components/layout/InfoPageLayout";
import { usePageMetadata } from "@/hooks/usePageMetadata";
import { getStaticPageMetadata } from "@/lib/pageMetadata";

export default function Methodology() {
  usePageMetadata({
    title: "Content Methodology and Review Standards",
    path: "/methodology",
    description:
      "See how Shank Strategy Ops researches, reviews, updates, and quality-checks essays and tool writeups before publication.",
    structuredData: {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: "Methodology",
      url: absoluteUrl("/methodology"),
      description:
        "Methodology page describing sourcing, testing, review, and update standards for Shank Strategy Ops.",
    },
  });

  return (
    <InfoPageLayout
      eyebrow="HOW WE WORK"
      title="Original pages need an operating method behind them."
      lede="This site is intentionally small enough to review by hand. Every page should be understandable, attributable, and worth a reader's time without depending on autogenerated filler."
    >
      <InfoCard
        title="How essays are built"
        body={[
          "Essays begin with a real operating question, an experiment, or a claim worth arguing. They are drafted around a defined thesis, then expanded with examples, constraints, and counterpressure. The standard is simple: the reader should leave with a clearer model of the problem than they had before.",
          "Posts are not assembled from scraped summaries or stitched search snippets. If a piece references outside work, it should add interpretation, synthesis, and practical framing that did not exist in the source material by itself.",
        ]}
      />

      <InfoCard
        title="Source and evidence standards"
        body={[
          "Source quality matters more here than source count. When a piece depends on a factual claim, the preferred order is direct observation, primary documentation, first-party data, and only then secondary commentary.",
          "When exact certainty is not available, assumptions are stated plainly. When a number or claim is approximate, that uncertainty should be visible instead of hidden behind confident marketing language.",
        ]}
        bullets={[
          "Primary and first-party sources are preferred whenever possible",
          "Unsupported claims should be removed rather than padded",
          "Summaries should preserve the original meaning instead of flattering the argument",
        ]}
      />

      <InfoCard
        title="How tools are evaluated"
        body={[
          "Tools listed on this site are chosen because they solve a concrete problem in operations or engineering. They should be explainable, testable, and shaped by real constraints such as cost, latency, reliability, privacy, or auditability.",
          "A tool page should tell a reader what problem exists, how the tool addresses it, who it is for, and where the boundaries are. If a tool cannot clear that bar, it does not belong here.",
        ]}
      />

      <InfoCard
        title="Human review and AI usage"
        body={[
          "Human review is required before publication. AI may be used as a drafting aid, comparison tool, or editing assistant, but the site does not publish unattended AI output as finished editorial content.",
          "The accountable standard is publisher review: every page should be checked for clarity, factual drift, formatting, and whether it says something specific enough to justify existing at all.",
        ]}
        note="The rule is not 'never use AI.' The rule is 'do not outsource judgment.'"
      />

      <InfoCard
        title="Updates and corrections"
        body={[
          "Important pages should be revised when underlying facts, links, or recommendations change materially. If a page is outdated, it should be refreshed, redirected, or removed instead of left to decay.",
          "When a meaningful error is discovered, the page should be corrected directly and the new version should remain more useful than the old one. Silent rot is not an acceptable content strategy.",
        ]}
      />
    </InfoPageLayout>
  );
}
