import { Link } from "wouter";
import { siteConfig } from "@/lib/site";

const footerLinks = [
  { href: "/about", label: "About" },
  { href: "/methodology", label: "Methodology" },
  { href: "/editorial-policy", label: "Editorial Policy" },
  { href: "/privacy", label: "Privacy" },
  { href: "/terms", label: "Terms" },
];

export default function SiteFooter() {
  return (
    <footer className="py-12 bg-brand-black border-t border-border">
      <div className="container">
        <div className="grid gap-8 lg:grid-cols-[1.4fr_1fr_1fr] lg:items-start">
          <div>
            <Link href="/" className="flex items-center gap-3">
              <div className="w-8 h-8 bg-brand-orange flex items-center justify-center">
                <span className="font-display font-bold text-brand-black">S</span>
              </div>
              <span className="font-display font-bold tracking-tight">{siteConfig.name}</span>
            </Link>

            <p className="mt-4 max-w-md font-body text-sm leading-relaxed text-brand-offwhite/65">
              Strategy execution, operational excellence, original essays, and open-source
              tools for teams that need clarity, accountability, and durable systems.
            </p>
          </div>

          <div>
            <p className="font-mono text-xs tracking-[0.24em] text-brand-orange">SITE</p>
            <div className="mt-4 flex flex-col gap-3">
              {footerLinks.map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  className="font-body text-sm text-brand-offwhite/65 transition-colors hover:text-brand-orange"
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>

          <div>
            <p className="font-mono text-xs tracking-[0.24em] text-brand-orange">CONTACT</p>
            <div className="mt-4 space-y-3">
              <p className="font-body text-sm text-brand-offwhite/65">
                Editorial, business, and partnership inquiries:
              </p>
              <a
                href={`mailto:${siteConfig.email}`}
                className="font-body text-sm text-brand-offwhite transition-colors hover:text-brand-orange"
              >
                {siteConfig.email}
              </a>
              <a
                href="mailto:ashlee.wishmyer@gmail.com"
                className="font-body text-sm text-brand-offwhite transition-colors hover:text-brand-orange"
              >
                Ashlee@shankstrategy.com
              </a>
            </div>
          </div>
        </div>

        <div className="mt-10 flex flex-col gap-3 border-t border-brand-offwhite/10 pt-6 md:flex-row md:items-center md:justify-between">
          <p className="font-mono text-sm text-brand-offwhite/50">
            &copy; {new Date().getFullYear()} {siteConfig.name}. All rights reserved.
          </p>
          <p className="font-body text-sm text-brand-offwhite/45">
            Original publisher-owned content. No autogenerated page farms. No syndicated filler.
          </p>
        </div>
      </div>
    </footer>
  );
}
